USE [master]
GO

/****** Object:  Database [StudentDB]    Script Date: 10/3/2022 9:58:52 AM ******/
CREATE DATABASE [StudentDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StudentDB', FILENAME = N'D:\MSSQL12.SQLEXPRESS\MSSQL\DATA\StudentDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'StudentDB_log', FILENAME = N'D:\MSSQL12.SQLEXPRESS\MSSQL\DATA\StudentDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [StudentDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StudentDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StudentDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StudentDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StudentDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StudentDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StudentDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [StudentDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StudentDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StudentDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StudentDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StudentDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StudentDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StudentDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StudentDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StudentDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StudentDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StudentDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StudentDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StudentDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StudentDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StudentDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StudentDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StudentDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StudentDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StudentDB] SET  MULTI_USER 
GO

ALTER DATABASE [StudentDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StudentDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StudentDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StudentDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [StudentDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StudentDB] SET  READ_WRITE 
GO

